version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"

    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Etc/UTC"

    open-pull-requests-limit: 5

    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    commit-message:
      prefix: "chore"
      include: "scope"
