version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"

    schedule:
      interval: "weekly"

    open-pull-requests-limit: 10

    groups:
      patches:
        update-types:
          - "patch"

    commit-message:
      prefix: "chore"
