# Generated by Django 4.2 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmessagessettings",
            name="footer_newsletter_signup_link",
            field=models.CharField(
                blank=True,
                help_text="Path to the newsletter Wagtail form page. If left blank, the signup CTA will not be displayed.",
                max_length=255,
            ),
        ),
    ]
