# Generated by Django 5.1.15 on 2026-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletopic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
